import Head from 'next/head'





const Main = props =>{
    return(<>
    
    <h1 className="bg-black hover:bg-white">Your are in main Page</h1>
    <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>);

}
export default Main;